__title__ = "pyrtma"
__description__ = "A Python client for RTMA/Dragonfly"
__url__ = "https://github.com/pitt-rnel/pyrtma"
__version__ = "1.2.3"
__author__ = "RNEL"
__author_email__ = ""
__license__ = "MIT"
__copyright__ = "University of Pittsburgh Rehab Neural Engineering Labs, 2023"
